/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.libndt.swig;

public class LibndtJNI {
  public final static native long versionMajor_get();
  public final static native long versionMinor_get();
  public final static native long versionPatch_get();
  public final static native short nettestFlagUpload_get();
  public final static native short nettestFlagDownload_get();
  public final static native short nettestFlagDownloadExt_get();
  public final static native long verbosityQuiet_get();
  public final static native long verbosityWarning_get();
  public final static native long verbosityInfo_get();
  public final static native long verbosityDebug_get();
  public final static native long protocolFlagJson_get();
  public final static native long protocolFlagTls_get();
  public final static native long protocolFlagWebsockets_get();
  public final static native void SwigSettings_mlabnsUrl_set(long jarg1, SwigSettings jarg1_, String jarg2);
  public final static native String SwigSettings_mlabnsUrl_get(long jarg1, SwigSettings jarg1_);
  public final static native void SwigSettings_timeout_set(long jarg1, SwigSettings jarg1_, long jarg2);
  public final static native long SwigSettings_timeout_get(long jarg1, SwigSettings jarg1_);
  public final static native void SwigSettings_hostname_set(long jarg1, SwigSettings jarg1_, String jarg2);
  public final static native String SwigSettings_hostname_get(long jarg1, SwigSettings jarg1_);
  public final static native void SwigSettings_port_set(long jarg1, SwigSettings jarg1_, String jarg2);
  public final static native String SwigSettings_port_get(long jarg1, SwigSettings jarg1_);
  public final static native void SwigSettings_nettestFlags_set(long jarg1, SwigSettings jarg1_, short jarg2);
  public final static native short SwigSettings_nettestFlags_get(long jarg1, SwigSettings jarg1_);
  public final static native void SwigSettings_verbosity_set(long jarg1, SwigSettings jarg1_, long jarg2);
  public final static native long SwigSettings_verbosity_get(long jarg1, SwigSettings jarg1_);
  public final static native void SwigSettings_protocolFlags_set(long jarg1, SwigSettings jarg1_, long jarg2);
  public final static native long SwigSettings_protocolFlags_get(long jarg1, SwigSettings jarg1_);
  public final static native void SwigSettings_maxRuntime_set(long jarg1, SwigSettings jarg1_, long jarg2);
  public final static native long SwigSettings_maxRuntime_get(long jarg1, SwigSettings jarg1_);
  public final static native void SwigSettings_socks5hPort_set(long jarg1, SwigSettings jarg1_, String jarg2);
  public final static native String SwigSettings_socks5hPort_get(long jarg1, SwigSettings jarg1_);
  public final static native void SwigSettings_addMetadata(long jarg1, SwigSettings jarg1_, String jarg2, String jarg3);
  public final static native long new_SwigSettings();
  public final static native void delete_SwigSettings(long jarg1);
  public final static native long new_SwigClient__SWIG_0();
  public final static native long new_SwigClient__SWIG_1(long jarg1, SwigSettings jarg1_);
  public final static native void delete_SwigClient(long jarg1);
  public final static native boolean SwigClient_run(long jarg1, SwigClient jarg1_);
  public final static native void SwigClient_onWarning(long jarg1, SwigClient jarg1_, String jarg2);
  public final static native void SwigClient_onWarningSwigExplicitSwigClient(long jarg1, SwigClient jarg1_, String jarg2);
  public final static native void SwigClient_onInfo(long jarg1, SwigClient jarg1_, String jarg2);
  public final static native void SwigClient_onInfoSwigExplicitSwigClient(long jarg1, SwigClient jarg1_, String jarg2);
  public final static native void SwigClient_onDebug(long jarg1, SwigClient jarg1_, String jarg2);
  public final static native void SwigClient_onDebugSwigExplicitSwigClient(long jarg1, SwigClient jarg1_, String jarg2);
  public final static native void SwigClient_onPerformance(long jarg1, SwigClient jarg1_, short jarg2, short jarg3, double jarg4, double jarg5, double jarg6, double jarg7);
  public final static native void SwigClient_onPerformanceSwigExplicitSwigClient(long jarg1, SwigClient jarg1_, short jarg2, short jarg3, double jarg4, double jarg5, double jarg6, double jarg7);
  public final static native void SwigClient_onResult(long jarg1, SwigClient jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native void SwigClient_onResultSwigExplicitSwigClient(long jarg1, SwigClient jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native void SwigClient_onServerBusy(long jarg1, SwigClient jarg1_, String jarg2);
  public final static native void SwigClient_onServerBusySwigExplicitSwigClient(long jarg1, SwigClient jarg1_, String jarg2);
  public final static native void SwigClient_director_connect(SwigClient obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void SwigClient_change_ownership(SwigClient obj, long cptr, boolean take_or_release);

  public static void SwigDirector_SwigClient_onWarning(SwigClient jself, String s) {
    jself.onWarning(s);
  }
  public static void SwigDirector_SwigClient_onInfo(SwigClient jself, String s) {
    jself.onInfo(s);
  }
  public static void SwigDirector_SwigClient_onDebug(SwigClient jself, String s) {
    jself.onDebug(s);
  }
  public static void SwigDirector_SwigClient_onPerformance(SwigClient jself, short tid, short nflows, double measured_bytes, double measurement_interval, double elapsed, double max_runtime) {
    jself.onPerformance(tid, nflows, measured_bytes, measurement_interval, elapsed, max_runtime);
  }
  public static void SwigDirector_SwigClient_onResult(SwigClient jself, String scope, String name, String value) {
    jself.onResult(scope, name, value);
  }
  public static void SwigDirector_SwigClient_onServerBusy(SwigClient jself, String msg) {
    jself.onServerBusy(msg);
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
