/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.libndt.swig;

public class SwigClient {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SwigClient(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SwigClient obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LibndtJNI.delete_SwigClient(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    LibndtJNI.SwigClient_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    LibndtJNI.SwigClient_change_ownership(this, swigCPtr, true);
  }

  public SwigClient() {
    this(LibndtJNI.new_SwigClient__SWIG_0(), true);
    LibndtJNI.SwigClient_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public SwigClient(SwigSettings settings) {
    this(LibndtJNI.new_SwigClient__SWIG_1(SwigSettings.getCPtr(settings), settings), true);
    LibndtJNI.SwigClient_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public boolean run() {
    return LibndtJNI.SwigClient_run(swigCPtr, this);
  }

  public void onWarning(String s) {
    if (getClass() == SwigClient.class) LibndtJNI.SwigClient_onWarning(swigCPtr, this, s); else LibndtJNI.SwigClient_onWarningSwigExplicitSwigClient(swigCPtr, this, s);
  }

  public void onInfo(String s) {
    if (getClass() == SwigClient.class) LibndtJNI.SwigClient_onInfo(swigCPtr, this, s); else LibndtJNI.SwigClient_onInfoSwigExplicitSwigClient(swigCPtr, this, s);
  }

  public void onDebug(String s) {
    if (getClass() == SwigClient.class) LibndtJNI.SwigClient_onDebug(swigCPtr, this, s); else LibndtJNI.SwigClient_onDebugSwigExplicitSwigClient(swigCPtr, this, s);
  }

  public void onPerformance(short tid, short nflows, double measured_bytes, double measurement_interval, double elapsed, double max_runtime) {
    if (getClass() == SwigClient.class) LibndtJNI.SwigClient_onPerformance(swigCPtr, this, tid, nflows, measured_bytes, measurement_interval, elapsed, max_runtime); else LibndtJNI.SwigClient_onPerformanceSwigExplicitSwigClient(swigCPtr, this, tid, nflows, measured_bytes, measurement_interval, elapsed, max_runtime);
  }

  public void onResult(String scope, String name, String value) {
    if (getClass() == SwigClient.class) LibndtJNI.SwigClient_onResult(swigCPtr, this, scope, name, value); else LibndtJNI.SwigClient_onResultSwigExplicitSwigClient(swigCPtr, this, scope, name, value);
  }

  public void onServerBusy(String msg) {
    if (getClass() == SwigClient.class) LibndtJNI.SwigClient_onServerBusy(swigCPtr, this, msg); else LibndtJNI.SwigClient_onServerBusySwigExplicitSwigClient(swigCPtr, this, msg);
  }

}
