/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.libndt.java;

public class NdtSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NdtSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NdtSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NdtLibraryJNI.delete_NdtSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMlabnsUrl(String value) {
    NdtLibraryJNI.NdtSettings_mlabnsUrl_set(swigCPtr, this, value);
  }

  public String getMlabnsUrl() {
    return NdtLibraryJNI.NdtSettings_mlabnsUrl_get(swigCPtr, this);
  }

  public void setTimeout(int value) {
    NdtLibraryJNI.NdtSettings_timeout_set(swigCPtr, this, value);
  }

  public int getTimeout() {
    return NdtLibraryJNI.NdtSettings_timeout_get(swigCPtr, this);
  }

  public void setHostname(String value) {
    NdtLibraryJNI.NdtSettings_hostname_set(swigCPtr, this, value);
  }

  public String getHostname() {
    return NdtLibraryJNI.NdtSettings_hostname_get(swigCPtr, this);
  }

  public void setPort(String value) {
    NdtLibraryJNI.NdtSettings_port_set(swigCPtr, this, value);
  }

  public String getPort() {
    return NdtLibraryJNI.NdtSettings_port_get(swigCPtr, this);
  }

  public void setNettestFlags(short value) {
    NdtLibraryJNI.NdtSettings_nettestFlags_set(swigCPtr, this, value);
  }

  public short getNettestFlags() {
    return NdtLibraryJNI.NdtSettings_nettestFlags_get(swigCPtr, this);
  }

  public void setVerbosity(long value) {
    NdtLibraryJNI.NdtSettings_verbosity_set(swigCPtr, this, value);
  }

  public long getVerbosity() {
    return NdtLibraryJNI.NdtSettings_verbosity_get(swigCPtr, this);
  }

  public void setProtocolFlags(long value) {
    NdtLibraryJNI.NdtSettings_protocolFlags_set(swigCPtr, this, value);
  }

  public long getProtocolFlags() {
    return NdtLibraryJNI.NdtSettings_protocolFlags_get(swigCPtr, this);
  }

  public void setMaxRuntime(int value) {
    NdtLibraryJNI.NdtSettings_maxRuntime_set(swigCPtr, this, value);
  }

  public int getMaxRuntime() {
    return NdtLibraryJNI.NdtSettings_maxRuntime_get(swigCPtr, this);
  }

  public void setSocks5hPort(String value) {
    NdtLibraryJNI.NdtSettings_socks5hPort_set(swigCPtr, this, value);
  }

  public String getSocks5hPort() {
    return NdtLibraryJNI.NdtSettings_socks5hPort_get(swigCPtr, this);
  }

  public void addMetadata(String k, String v) {
    NdtLibraryJNI.NdtSettings_addMetadata(swigCPtr, this, k, v);
  }

  public NdtSettings() {
    this(NdtLibraryJNI.new_NdtSettings(), true);
  }

}
